# Generated by Django 4.1.4 on 2023-01-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='added_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
