# Generated by Django 4.1.4 on 2023-01-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_blog_added_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='updated_on',
            field=models.DateField(auto_now=True),
        ),
    ]
