# Generated by Django 4.1.4 on 2023-01-04 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
