# Generated by Django 4.1.4 on 2023-01-05 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cart',
        ),
    ]
