# Generated by Django 4.1.4 on 2023-01-20 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60)),
                ('subject', models.CharField(max_length=30)),
                ('message', models.TextField(max_length=450)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
