# Generated by Django 4.1.4 on 2023-01-11 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_variation'),
        ('orders', '0002_remove_order_payment_remove_orderproduct_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='variation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.variation'),
            preserve_default=False,
        ),
    ]
