# Generated by Django 4.1.4 on 2023-01-05 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_alter_appuser_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
