# Generated by Django 4.1.4 on 2023-01-06 22:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='times_used',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
