# Generated by Django 4.1.4 on 2023-01-07 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_checkout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkout',
        ),
    ]
