# Generated by Django 4.1.4 on 2022-12-27 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_appuser_is_staff_appuser_is_superadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='is_superadmin',
        ),
    ]
