# Generated by Django 4.1.4 on 2022-12-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_appuser_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='is_superadmin',
            field=models.BooleanField(default=False),
        ),
    ]
