# Generated by Django 4.1.4 on 2022-12-30 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_appuser_is_superadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='last_login',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
